# fly.toml app configuration file generated for reactivitiesis on 2023-06-26T14:11:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivitiesis"
primary_region = "bog"

[build]
  image = "izastawicka/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dd0rw0iej"
  Cloudinary__ApiKey="571546913534319"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
